version: 2.1
executors:
  android-executor:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run: echo "hello world" # `echo` コマンドを実行します